/* tool_layers.cpp - Layers panel */
#include "tools.h"
#include "tools_common.h"
#include "core/astro.h"
#include "core/theme.h"
#include "core/config.h"
#include "ui/labels.h"
#include "ui/tools/tools_settings.h"
#include <cmath>
#include <raylib.h>
#include "imgui.h"
#include "IconsFontAwesome6.h"

static const char *TRACK_LEGEND_KEY="groundtracks.legend";

void DrawPanelLayers(UIContext *ctx,AppConfig *cfg){(void)ctx;ImGui::PushTextWrapPos(0.0f);const float iw=24.0f;auto row=[&](const char*l,bool*v,const char*i,const char*t){ImGui::PushStyleColor(ImGuiCol_Text,ThemeColor(*v?g_theme.ui.ui_accent:g_theme.ui.text_secondary));ImU32 c=ImGui::GetColorU32(ImGuiCol_Text);ImVec2 s=ImGui::CalcTextSize(i),p=ImGui::GetCursorScreenPos();ImGui::GetWindowDrawList()->AddText(ImVec2(p.x+(iw-s.x)*0.5f,p.y),c,i);ImGui::PopStyleColor();ImGui::Dummy(ImVec2(iw,ImGui::GetFrameHeight()));ImGui::SameLine();ImGui::Checkbox(l,v);if(t&&ImGui::IsItemHovered())ImGui::SetTooltip("%s",t);};row("Clouds",&cfg->show_clouds,ICON_FA_CLOUD,"Show cloud layer (C)");row("Night Lights",&cfg->show_night_lights,ICON_FA_MOON,"Show night-side city lights (N)");row("Markers",&cfg->show_markers,ICON_FA_MAP_PIN,"Show ground markers (L)");row("Scattering",&cfg->show_scattering,ICON_FA_SUN,"Atmospheric scattering effect");row("Skybox",&cfg->show_skybox,ICON_FA_STAR,"Show starfield skybox");row("Highlight Sunlit",&cfg->highlight_sunlit,ICON_FA_BOLT,"Highlight sunlit portions of orbits");row("Slant Range",&cfg->show_slant_range,ICON_FA_RULER,"Show slant range line to home");row("Ground Coverage",&cfg->show_ground_coverage,ICON_FA_ROUTE,"Show the line-of-sight ground coverage footprint");row("Apsides",&cfg->show_apsides,ICON_FA_CIRCLE_DOT,"Show perigee/apogee markers and altitude labels");bool legend=ToolSettingGetBool(cfg,TRACK_LEGEND_KEY,true);if(ImGui::Checkbox("Track Legend",&legend))ToolSettingSetBool(cfg,TRACK_LEGEND_KEY,legend);ImGui::Separator();bool labels=ToolSettingGetBool(cfg,LABELS_KEY_ENABLED,true);if(ImGui::Checkbox("Labels",&labels))ToolSettingSetBool(cfg,LABELS_KEY_ENABLED,labels);int mode=ToolSettingGetInt(cfg,LABELS_KEY_MODE,LABELS_MODE_ACTIVE_ONLY);const char*modes[]={"Active only","All","None"};ImGui::SetNextItemWidth(-1);if(ImGui::Combo("##label_mode",&mode,modes,3))ToolSettingSetInt(cfg,LABELS_KEY_MODE,mode);bool alt=ToolSettingGetBool(cfg,LABELS_KEY_ALTITUDE,false);if(ImGui::Checkbox("Label Altitude",&alt))ToolSettingSetBool(cfg,LABELS_KEY_ALTITUDE,alt);float size=ToolSettingGetFloat(cfg,LABELS_KEY_SIZE,1.0f);if(ImGui::SliderFloat("Label Size",&size,0.5f,1.5f,"%.2fx"))ToolSettingSetFloat(cfg,LABELS_KEY_SIZE,size);bool bg=ToolSettingGetBool(cfg,LABELS_KEY_BG,true);if(ImGui::Checkbox("Label Background",&bg))ToolSettingSetBool(cfg,LABELS_KEY_BG,bg);int maxc=ToolSettingGetInt(cfg,LABELS_KEY_MAX_COUNT,200);if(ImGui::SliderInt("Max Labels",&maxc,10,1000))ToolSettingSetInt(cfg,LABELS_KEY_MAX_COUNT,maxc);ImGui::PopTextWrapPos();}

static void past_track(const SceneContext*s,Satellite*sat){if(sat->mean_motion<=0)return;constexpr int n=400;Vector2 p[n+1];double period=(2.0*PI/sat->mean_motion)/86400.0,step=period/n;for(int j=0;j<=n;++j){double t=s->current_epoch-(n-j)*step;Vector3 r=calculate_position(sat,get_unix_from_epoch(t));get_map_coordinates(r,epoch_to_gmst(t),s->earth_rotation_offset,s->map_w,s->map_h,&p[j].x,&p[j].y);}Color c=(sat==s->active_sat)?g_theme.world.orbit_highlighted:g_theme.world.orbit_normal;c.a=(unsigned char)(c.a*0.55f);for(int o=-1;o<=1;++o){float xo=o*s->map_w;for(int j=1;j<=n;++j){if(((j/4)&1)||fabsf(p[j].x-p[j-1].x)>=s->map_w*0.6f)continue;DrawLineEx({p[j-1].x+xo,p[j-1].y},{p[j].x+xo,p[j].y},2.0f/s->camera2d->zoom,c);}}}
static void legend(const SceneContext*s,int sx,int sy){float iz=1.0f/s->camera2d->zoom;Vector2 tl=GetScreenToWorld2D({(float)sx+12,(float)sy+12},*s->camera2d);Rectangle r={tl.x,tl.y,154*iz,68*iz};Color bg=g_theme.world.bg;bg.a=205;DrawRectangleRec(r,bg);DrawRectangleLinesEx(r,iz,g_theme.ui.window_border);float x1=tl.x+9*iz,x2=x1+30*iz,tx=x2+8*iz,y=tl.y+14*iz,fs=12*iz;Color future=g_theme.world.orbit_normal,past=future;past.a=(unsigned char)(past.a*0.55f);for(int d=0;d<4;++d)DrawLineEx({x1+d*8*iz,y},{x1+d*8*iz+4*iz,y},2*iz,past);DrawTextEx(GetFontDefault(),"Past",{tx,y-6*iz},fs,iz,g_theme.ui.text_main);y+=18*iz;DrawCircleV({(x1+x2)*0.5f,y},3.5f*iz,g_theme.world.sat_highlighted);DrawTextEx(GetFontDefault(),"Current",{tx,y-6*iz},fs,iz,g_theme.ui.text_main);y+=18*iz;DrawLineEx({x1,y},{x2,y},2*iz,future);DrawTextEx(GetFontDefault(),"Future",{tx,y-6*iz},fs,iz,g_theme.ui.text_main);}
void DrawSceneLayers(SceneContext*s,AppConfig*cfg){if(!s->is_2d_view||!s->camera2d||s->is_pov_mode)return;Vector2 mn=GetWorldToScreen2D({-s->map_w/2,-s->map_h/2},*s->camera2d),mx=GetWorldToScreen2D({s->map_w/2,s->map_h/2},*s->camera2d);int x=(int)mn.x,y=(int)mn.y,w=(int)(mx.x-mn.x),h=(int)(mx.y-mn.y);if(x<0){w+=x;x=0;}if(y<0){h+=y;y=0;}if(x+w>GetScreenWidth())w=GetScreenWidth()-x;if(y+h>GetScreenHeight())h=GetScreenHeight()-y;if(w<=0||h<=0)return;BeginScissorMode(x,y,w,h);for(int i=0;i<sat_count;++i)if(satellites[i].is_active)past_track(s,&satellites[i]);if(ToolSettingGetBool(cfg,TRACK_LEGEND_KEY,true))legend(s,x,y);EndScissorMode();}
